CREATE TABLE IF NOT EXISTS HIGHLIGHT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    author VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    quote VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
